### ISSUE TITLE
Settings not updating on restart

### ISSUE THREAD

**Issue by thecrazy13** [mipen/BannerlordTweaks#51]
With the new update when you set your settings and then restart, if you go check on the settings, they are back at the BannerlordTweaks default, as if you never touched them at all.

**Comment by thecrazy13** [comment]
![image](https://user-images.githubusercontent.com/23746741/79564382-8a21ea80-807c-11ea-988c-83f426a22cbd.png)
Menu also shows "ERROR" at top.

**Comment by Dextradamusz** [comment]
I disabled the FixedLauncher mod which I had activated while having this issue, and now shows propper setup layout, settings remainning the way you set it after restart.

**Comment by thecrazy13** [comment]
> I disabled the FixedLauncher mod which I had activated while having this issue, and now shows propper setup layout, settings remainning the way you set it after restart.

Welp
I tried doing that and broke my game permanently, guess I gotta reinstall everything now.

**Comment by Dextradamusz** [comment]
> > I disabled the FixedLauncher mod which I had activated while having this issue, and now shows propper setup layout, settings remainning the way you set it after restart.
> 
> Welp
> I tried doing that and broke my game permanently, guess I gotta reinstall everything now.

Awh, that sucks.
I must tell you 2 things regarding this, your game most likely 'broke' because of the incorrect load order of your mods, which resets everytime you open the default launcher... VERY tedious.
The other is that I found out this workaround did not have the desired effects so I looked into the issue more and found that I did not unblock the module folders DLL files with powershell. The method of doing this is on the Nexusmods site of this particular mod.
Afterwards I used the Fixedlauncher again. finding that the game loaded but the issue persisted.
Looking into it more I found that another mod called DCC, Detailed Character Creation appearantly meeses up the propper saving of settings for mods using ModLib. SO! I deactivated that mod, did the Tweaks settings in the main menu again, restarted game and.. Voilá! It's works now.

I hope this helps you, if even a little.

**Comment by 3rickbat** [comment]
I seem to having the same issue, but I never had DCC in the first place. There might be another mod that is incompatible. I do use the fixed launcher, however. Perhaps the Community Patch is the issue, since they also add another options menu to the opening screen, but that's just a stab in the dark. Either way, it does seem to be a problem that I'm unable to fix.

**Comment by Dextradamusz** [comment]
Load order, mod incompatibility, DLL  unblocking. Did you check each 3 of these options?

**Comment by 3rickbat** [comment]
Yeah definitely did DLL unblocking.  For load order, I put modlib above tweaks right? For incompatibility, is there anything I should be aware of?

**Comment by Dextradamusz** [comment]
For me is was only DCC being incompatible but I came across  another mod  on the NExus which mentioned being incompatible with  tweaks, so I didnt Download it, and so I don't remember which mod it was. You may wanna check all your mods related nexus page and check one by one.
I know.. Tedious. But that's all I can come up with for you now at this point, apolegies for that.

**Comment by 3rickbat** [comment]
It's all good, any help is appreciated. I'll double check what I have.
