### ISSUE TITLE
Smithing Crash

### ISSUE THREAD

**Issue by Thormodor** [mipen/BannerlordTweaks#54]
Hello. 
After the recent Updates when attempting to access smithing page in a city game crashes. removing Bannerlord Tweaks stops this crash. 
As always Great work on the mod i find it to be a must when playing.

**Comment by ZaZiiZu** [comment]
the devs changed the return type of some method used in the mod.
It's a pretty easy fix, since using the updated MBB dll-files the mod doesn't even build due to that mismatch.

I never used git for public code, so never tried the whole "Pull request"-thingy.
I'll be faster for the maintainer to fix it himself instead of accepting my pull-request anyways :D

**Comment by mipen** [comment]
The mod isn't currently compatible with beta 1.2. I will hopefully do a beta 1.2 version if I have the time, but for now disable the smelting tweaks (learn parts from smelted items and hide locked items in smelting view)
